version: '3.3'

services:

  #############################################################
  ######################### SERVICE ###########################
  #############################################################

  fan-club-need-for-speed:
    image: 'lucazz18/fan-club-need-for-speed-service:latest'
#    networks:
#      - fuji-network
    ports:
      - "8089:8089"
#    environment:
#      EUREKA_URL: fan-club-need-for-speed-service
#      EUREKA_DEFAULT_ZONE: 'http://eureka-service:8761/eureka'


#############################################################
######################### NETWORK ###########################
#############################################################
networks:
  fuji-network:
    driver: "bridge"