eureka:
  instance:
    hostname: ${EUREKA_URL:localhost}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: fanclubneedforspeed
          uri: lb://FAN-CLUB-NEED-FOR-SPEED-SERVICE
          predicates:
            - Path=/api/**
            - Path=/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"


